version: "3.3"

services:
  client:
    build:
      context: ./client
      args:
        - node_env=development
    container_name: client_app
    ports:
      - '8080'
    volumes:
      - ./client:/client_app
    env_file:
        - env.list

  server:
    build:
      context: ./server
      args:
        - rack_env=development
    container_name: server_app
    command: ["migrate", "start"]
    ports:
      - "3000"
    env_file:
      - env.list
    depends_on:
      - db
    volumes:
      - ./server:/server_app

  db:
    image: postgres
    container_name: db
    env_file:
      - env.list
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - client
