source "https://rubygems.org"

gem 'sinatra'
gem 'puma'
gem 'json'
gem 'dotenv', require: 'dotenv/load'
gem 'sequel'
gem 'pg'
gem 'rake'

group :test, :development do
  gem 'pry'
  gem 'rerun'
end

group :test do
  gem 'rack-test', require: 'rack/test'
  gem 'rspec'
  gem 'database_cleaner'
end
