require 'rubygems'
require 'bundler/setup'

require 'rake'

host     = ENV['DB_HOST']
database = ENV['POSTGRES_DB']
user     = ENV['POSTGRES_USER']
password = ENV['POSTGRES_PASSWORD']

connection = "postgres://#{user}:#{password}@#{host}/#{database}"

desc 'run server'
task :start do
  if ENV["RACK_ENV"] === 'production'
    sh "puma -p 3000"
  else
    sh "rerun --background -- rackup -p 3000 -o 0.0.0.0"
  end
end

desc 'run console'
task :console do
  sh "sequel #{connection} -L 'models'"
end

desc 'migrate schema'
task :migrate do
  sh "sequel -m db/migrations #{connection}"
end

desc 'run tests'
task :test do
  sh "rspec --require spec_helper --color --format documentation"
end